### ISSUE TITLE
Create grid of evenly spaced points to sample

### ISSUE THREAD

**Issue by gracelewin** [cropmosaiks/.github#88]

**Comment by cullen-molitor** [comment]
https://stackoverflow.com/questions/70883956/how-can-i-sample-every-other-value-in-a-grid-while-ensuring-it-alternates-each-r

**Comment by cullen-molitor** [comment]
Grid and sampling solved, but the points are not featurizing correctly now

**Comment by cullen-molitor** [comment]
Points are now featurizing correctly
