### ISSUE TITLE
Model optimization testing (number of features/cell size) - testing all over months 3-6

### ISSUE THREAD

**Issue by gracelewin** [cropmosaiks/.github#97]

**Comment by gracelewin** [comment]
Noticed features are duplicated, need to fix this issue before conducting the model optimization testing

**Comment by cognack** [comment]
Features optimization spreadsheet created to track model optimization
https://docs.google.com/spreadsheets/d/1s0lCwHKscYII2Y2fRg-BUcnjXnNcjzBgWMFBcS4_qNs/edit#gid=0
